### ISSUE TITLE
Tagged release

### ISSUE THREAD

**Issue by ezzatron** [realityking/hash_equals#1]
I'd like to use this library, but I would feel much more confident if there was a tagged release I could use. Is it ready to be tagged?

Thanks.

**Comment by realityking** [comment]
I will create a tag once 5.6 has been released and I've made sure all of PHP's tests also pass with this library. I don't want to release anything as stable that potentially doesn't match what PHP is shipping.

**Comment by ezzatron** [comment]
Just bumping this since 5.6 has been released.
